# ========== Appearance ==========
font_family JetBrainsMono Nerd Font
font_size 20.0
bold_font auto
italic_font auto
adjust_line_height 105%

background              #0f0f17
foreground              #d1d1e0
background_opacity      0.92
background_blur         3

cursor                  #89b4fa
cursor_shape            beam
cursor_blink_interval   0.6

window_padding_width    12
window_border_width     1
inactive_border_color   #1a1a25
active_border_color     #89b4fa
hide_window_decorations yes

color0  #15161e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

selection_foreground    #1a1b26
selection_background    #7aa2f7

scrollback_lines 10000
enable_audio_bell no
map ctrl+shift+enter new_wi_
