# Kitty configuration file

# Font size
font_size 12

# Enable Ctrl+Shift+C and Ctrl+Shift+V for copy/paste
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# Cursor style
cursor_shape block

# Colors (example)
background #1d1f21
foreground #c5c8c6

# disable the terminal bell
bell none

# map C-arrowleft and C-arrowright to skip a full word
map ctrl+left send_text all \x1b[1;5D
map ctrl+right send_text all \x1b[1;5C
