# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        colors = true
        interval = 10
	color_good="#69CE69"
	color_degraded="#EBCB8B"
	color_bad="#BF616A"
}

order += "volume master"
order += "ipv6" # if any
# order += "cpu_temperature 0"
order += "cpu_usage"
order += "disk /"
order += "wireless _first_"
order += "ethernet _first_" # if any
order += "memory"
order += "battery all"
# order += "load"
order += "tztime local"

volume master {
        format = "vol: %volume "
        format_muted = "vol: muted (%volume) "
        device = "default"
}

ipv6 {
        format_up = " useless protocol: %ipv6 "
        format_down = ""
}

cpu_temperature 0 {
        format = " CPU temp: %degrees °C "
	color_good = "#00FF00"
	color_degraded = "#FFFF00"
	color_bad = "#FF0000"
}

cpu_usage {
	format = " CPU usage: %usage "
}

disk "/" {
        format = " disk: %avail "
}

wireless _first_ {
        # format_up = "wifi: (%quality at %essid) %ip"
        format_up = " wifi:%quality - leaked IP: %ip "
        format_down = " wifi: off "
}

ethernet _first_ {
        # if you use %speed, i3status requires root privileges
        # format_up = "E: %ip (%speed)"
        format_up = " ethernet: %speed - leaked IP: %ip "
	format_down = ""
}

memory {
       memory_used_method = classical
       format=" RAM: %used/%total "
}

battery all {
        format = " battery: %percentage (%remaining) " # %status
	last_full_capacity = true
	threshold_type=percentage
	low_threshold=20
}

load {
        format = " load: %1min "
	color_good = "#00FF00"
	color_bad = "#FF0000"
}

tztime local {
        format = " %d-%m %H:%M "
}
